dist: xenial

env:
  - CI=true

branches:
  only:
  - master

language: ruby

services:
  - docker

before_install:
- apt install ./dive_0.7.2_linux_amd64.deb
- docker build -t chefaustin/gem-jar .
- docker run --name gem-jar -p 9292:9292 -v $(pwd)/db:/root/.gemstash chefaustin/gem-jar:latest

script:
- bundle exec rake test
